apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: fomo-sample
spec:
  groups:
    - name: slack_settings
      title: My Slack Config
      description: Configuration to connect the Slack Channel Created bot to your Slack workspace
      items:
        - name: slack_bot_token
          title: Slack Bot Token
          help_text: The Bot User OAuth Token from your Slack custom app
          type: password
          required: true
        - name: slack_signing_secret
          title: Slack Signing Secret
          help_text: The Signing Secret from your Slack custom app
          type: password
          required: true
        - name: slack_channel_id
          title: Slack Channel Id
          help_text: Open your slack workspace in your browser, and open the channel where you expect the fomo messages to appear. In the address bar the last part is the channel id.
          type: password
          required: true
