apiVersion: v1
kind: Service
metadata:
  name: slack-channel-created-fomo
  namespace: '{{repl ConfigOption "namespace" }}'
  labels:
    app: slack-channel-created-fomo-config
    component: notifier
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: slack-channel-created-fomo
    component: notifier
