apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
  labels:
    app: slack
type: Opaque
data:
  bot-token: '{{repl ConfigOption "slack_bot_token" | Base64Encode}}'
  signing-secret: '{{repl ConfigOption "slack_bot_token" | Base64Encode}}'
  channel-id: '{{repl ConfigOption "slack_channel_id" | Base64Encode}}'
