apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app=slack-channel-created-fomo
          - component=notifier
        namespace: '{{repl ConfigOption "namespace" }}'
        limits:
          maxAge: 30d
          maxLines: 10000
