apiVersion: v1
kind: Service
metadata:
  name: {{ include "slackfomo.fullname" . }}
  labels:
    {{- include "slackfomo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "slackfomo.selectorLabels" . | nindent 4 }}
